### ISSUE TITLE
Recommend package name change

### ISSUE THREAD

**Issue by lorezyra** [AsemAlhaidary/hexo-db-generator#1]
Instead of `hexo-db-generator`, recommend calling this `hexo-generator-database` to match the HEXO naming scheme.

Also, recommend reviewing existing plugins before building a new one. There's a good chance someone may have already built something better (or sufficient) for our needs. For example: https://github.com/alexbruno/hexo-generator-json-content...

**Comment by AsemAlhaidary** [comment]
Okay, good idea.

Thank you 👍
